# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "nvme" "usbhid" "uas" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/18e1144a-daa3-4315-a51c-848a03f70d5b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-f2ced643-3fc0-44b2-aa56-b26b16c29f2a".device = "/dev/disk/by-uuid/f2ced643-3fc0-44b2-aa56-b26b16c29f2a";

  fileSystems."/boot/efi" =
    { device = "/dev/disk/by-uuid/C6DC-5AB5";
      fsType = "vfat";
    };

  swapDevices =
    [ 
      { 
        device = "/dev/disk/by-uuid/82781f4e-8e91-4687-927d-7c870058cdef"; 
      }
      {
        device = "/var/lib/swapfile";
        size = 75 * 1024;
      }
    ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
